### ISSUE TITLE
assets/lie.mp3 not found

### ISSUE THREAD

**Issue by dyllandry** [wlto/music-visualizer#2]
This resource is not included with the repo, so I cannot run it. Vicky was interested in what Github was, and she wanted to try this out, but it didnt work. 😩

**Comment by wlto** [comment]
looool sorry i just saw this today lol @dyllandry how come GitHub didn't tell me

**Comment by wlto** [comment]
@dyllandry okay i fixed it with the instructions in the README :). I prevented the `assets` directory to be pushed for music copyright purpose :)
